### ISSUE TITLE
폴더 api만들기

### ISSUE THREAD

**Issue by John3210of** [hanghae-flowing/Back-end#136]

**Comment by jeonbar2** [comment]
프로젝트랑 폴더 중복된거 프로젝트부분에서 안보이게해주기
폴더 조회할떄 trash부분도 넣어서 보내주기 
 폴더에 중복해서 프로젝트가 들어감..

폴더삭제할경우에 프로젝트 장일경우 프로젝트삭제, 멤버일경우 멤버탈퇴

**Comment by jeonbar2** [comment]
선택한 폴더의 프로젝트 리스트 뽑아오기부분 오류
