### ISSUE TITLE
db 테이블 cascading 이슈...

### ISSUE THREAD

**Issue by John3210of** [hanghae-flowing/Back-end#98]
좋댔다............ 아 ....... ㅋㅋㅋㅋ

**Comment by jeonbar2** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by John3210of** [comment]
96번에서 몇개 작업할것임
프로젝트<>노드테이블
프로젝트<>다큐먼트
프로젝트 <> 스왓
스왓 <>    s,
	         w,
	         o,
	         t
